apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: react-frontend
    context: ./react
  - image: node-api
    context: ./node
  local:
    push: false

deploy:
  helm:
    flags:
      upgrade: ["--timeout", "600", "--namespace", "toolchain"]
      install: ["--timeout", "600", "--namespace", "toolchain"]
    releases:
    - name: springtrader 
      chartPath: ./charts/apprentice-outreach
      values:
        react.image: react-frontend
        node.image: node-api 
      setValueTemplates:
        istioDomain: "{{.ISTIO_DOMAIN}}"

