apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: react-frontend
    context: ./react
  - image: node-api
    context: ./node
deploy:
  helm:
    releases:
    - name: apprentice-outreach 
      chartPath: charts/apprentice-outreach
      values:
        react.image: react-frontend
        node.image: node-api
      setValueTemplates:
        istioDomain: "{{.ISTIO_DOMAIN}}"
        react.host: "{{.REACT_APP_IP}}"
