apiVersion: skaffold/v1beta12
kind: Config
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: react-frontend
    context: ./react
  - image: node-api
    context: ./node
deploy:
  helm:
    releases:
    - name: apprentice-outreach 
      chartPath: charts/apprentice-outreach
      values:
        react.image: react-frontend
        node.image: node-api
      setValueTemplates:
        istio.enabled: true
        istio.domain: "{{.ISTIO_DOMAIN}}"
        node.url: "{{.API_URL}}"
profiles:
- name: local
  activation:
  - kubeContext: docker-desktop
  patches:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/storageClassName
      value: hostpath
    - op: replace
      path: /deploy/helm/releases/0/setValueTemplates/istio.enabled
      value: false
    - op: replace
      path: /deploy/helm/releases/0/setValueTemplates/node.url
      value: http://localhost:3001/api/
      

