{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  rules:
    - host: '{{- .Chart.Name }}.{{- required "ingress.domain is required!" .Values.ingress.domain }}'
      http:
        paths:
          - path: '/'
            backend:
              serviceName: outreach-frontend
              servicePort: frontend
          - path: '/api'
              serviceName: outreach-node-api
              servicePort: node-api
{{- end }}
