{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
  - {{ .Chart.Name }}.{{ .Values.istio.domain }}
  gateways:
  - istio-system/app-gateway
  http:
  - match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: outreach-node-api
        port:
          number: 3001
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: outreach-frontend
        port:
          number: 3000
{{ end }}